version: '3'
services:
  server:
    image: openmined/pis:latest
    build: ./server/
    volumes: ['./server:/app']
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    ports:
      - 5000:5000
