version: '3'
services:
  server:
    image: openmined/pis:latest
    build: ./server/
    volumes: ['./server:/server']
    restart: always
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      DB_URI: postgresql://postgres:pis_local_5432@db:5432
    ports:
      - 5000:5000
  db:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: pis_local_5432
    ports:
      - 5432:5432
